# Generated by Django 3.1.5 on 2021-01-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(),
        ),
    ]
