# Generated by Django 3.1.5 on 2021-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20210113_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='description',
            new_name='course_description',
        ),
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='workshops',
            field=models.ManyToManyField(blank=True, to='registration.Workshop'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='workshop_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
