# Generated by Django 3.1.5 on 2021-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210113_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='created_updated_date',
            new_name='last_modified_date',
        ),
        migrations.AlterField(
            model_name='student',
            name='graduation_date',
            field=models.DateField(),
        ),
    ]
